name: Kaizen VPN

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          submodules: 'recursive'

      - name: Set up Java
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt' # Adjust this to your project's Java version

      - name: Set up Flutter SDK
        run: |
          git clone https://github.com/flutter/flutter.git
          export PATH="$PATH:${{ github.workspace }}/flutter/bin"
          flutter config --no-analytics
          flutter doctor
          flutter doctor -v
          flutter doctor
        working-directory: ${{ github.workspace }}
        env:
          FLUTTER_HOME: ${{ github.workspace }}/flutter

      - name: Build APK
        run: |
          chmod +x ${{ github.workspace }}/gradlew
          ${{ github.workspace }}/gradlew assembleDebug
        working-directory: ${{ github.workspace }}

      - name: Upload APK
        uses: actions/upload-artifact@v2
        with:
          name: app-debug
          path: app/build/outputs/apk/debug/app-debug.apk
